const StateActionTypes = {
  GET_MAKES_START: "GET_MAKES_START",
  GET_MAKES_SUCCESS: "GET_MAKES_SUCCESS",
  GET_MAKES_FAILURE: "GET_MAKES_FAILURE",
  GET_MODELS_START: "GET_MODELS_START",
  GET_MODELS_SUCCESS: "GET_MODELS_SUCCESS",
  GET_MODELS_FAILURE: "GET_MODELS_FAILURE",
  GET_VEHICLES_START: "GET_VEHICLES_START",
  GET_VEHICLES_SUCCESS: "GET_VEHICLES_SUCCESS",
  GET_VEHICLES_FAILURE: "GET_VEHICLES_FAILURE",
};
